name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker build . --file Dockerfile --tag amenkhnissi/docker-test:Back-End-Development-Pictures
           docker login -u amenkhnissi -p  ${{ secrets.DOCKER_PASS }}
           echo "Logged successfully "
           docker push amenkhnissi/docker-test:Back-End-Development-Pictures
           echo "Successfully pushed"
      
